// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI1ZcE4CdWx1J7ZYVI6goEHWxNlJuv0-w',
    appId: '1:514447723789:web:3df557ffce4b210f5df444',
    messagingSenderId: '514447723789',
    projectId: 'chatapptute-be7c5',
    authDomain: 'chatapptute-be7c5.firebaseapp.com',
    storageBucket: 'chatapptute-be7c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAyS5K0U8CH4Fu3zMiXHPtY7ooCXDj5sU',
    appId: '1:514447723789:android:627d31e71c5057745df444',
    messagingSenderId: '514447723789',
    projectId: 'chatapptute-be7c5',
    storageBucket: 'chatapptute-be7c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCX3hreqir0GBsqeGFh5J1YDUOU4XIldg',
    appId: '1:514447723789:ios:334a55f354ce60275df444',
    messagingSenderId: '514447723789',
    projectId: 'chatapptute-be7c5',
    storageBucket: 'chatapptute-be7c5.firebasestorage.app',
    iosBundleId: 'com.example.chatt3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCX3hreqir0GBsqeGFh5J1YDUOU4XIldg',
    appId: '1:514447723789:ios:334a55f354ce60275df444',
    messagingSenderId: '514447723789',
    projectId: 'chatapptute-be7c5',
    storageBucket: 'chatapptute-be7c5.firebasestorage.app',
    iosBundleId: 'com.example.chatt3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI1ZcE4CdWx1J7ZYVI6goEHWxNlJuv0-w',
    appId: '1:514447723789:web:08b4c377e8c74a695df444',
    messagingSenderId: '514447723789',
    projectId: 'chatapptute-be7c5',
    authDomain: 'chatapptute-be7c5.firebaseapp.com',
    storageBucket: 'chatapptute-be7c5.firebasestorage.app',
  );
}
